export const stateOptions = [
  { id: 1, label: 'Acre' },
  { id: 2, label: 'Alagoas' },
  { id: 3, label: 'Amapá' },
  { id: 4, label: 'Amazonas' },
  { id: 5, label: 'Bahia' },
  { id: 6, label: 'Ceará' },
  { id: 7, label: 'Distrito Federal' },
  { id: 8, label: 'Espírito Santo' },
  { id: 9, label: 'Goiás' },
  { id: 10, label: 'Maranhão' },
  { id: 11, label: 'Mato Grosso' },
  { id: 12, label: 'Mato Grosso do Sul' },
  { id: 13, label: 'Minas Gerais' },
  { id: 14, label: 'Pará' },
  { id: 15, label: 'Paraíba' },
  { id: 16, label: 'Paraná' },
  { id: 17, label: 'Pernambuco' },
  { id: 18, label: 'Piauí' },
  { id: 19, label: 'Rio de Janeiro' },
  { id: 20, label: 'Rio Grande do Norte' },
  { id: 21, label: 'Rio Grande do Sul' },
  { id: 22, label: 'Rondônia' },
  { id: 23, label: 'Roraima' },
  { id: 24, label: 'Santa Catarina' },
  { id: 25, label: 'São Paulo' },
  { id: 26, label: 'Sergipe' },
  { id: 27, label: 'Tocantins' },
];
